CREATE USER wordle WITH PASSWORD 'wordle';
CREATE SCHEMA wordle;
GRANT ALL PRIVILEGES ON SCHEMA wordle TO wordle;
ALTER DEFAULT PRIVILEGES IN SCHEMA wordle GRANT ALL ON TABLES TO wordle;
ALTER DEFAULT PRIVILEGES IN SCHEMA wordle GRANT ALL ON SEQUENCES TO wordle;